### ISSUE TITLE
Unable to change settings

### ISSUE THREAD

**Issue by tomyaacov** [mdetools/mdetools19#1]
Hi,
I tried changing some of the settings (gameTime, player2Port) in the Settings.txt file and it didn't seem to affect the simulation (gameTime remained the default 240s). I ran it on MacOS. Do I need to do additional actions in order to change the settings in Settings.txt?

**Comment by GoGitThat** [comment]
Hi tomyaacov, there will be an update shortly that will allow you to specify the ports for each player. As for the other settings, that functionality will be available in a second release.

**Comment by moji1** [comment]
please redownload the simulation package.

**Comment by moji1** [comment]
Hi @tomyaacov 
Please let me know if I can close this issue?

Thanks
Mojtaba

**Comment by tomyaacov** [comment]
The simulation package doesn’t work now, at all (black screen when opening the app).

**Comment by GoGitThat** [comment]
Hi tom, another user recently pointed the issue out and hopefully it should be fixed in the newest release (link on the webpage should be updated), let me know if the issue still persists.

**Comment by moji1** [comment]
link for the fixed version: https://drive.google.com/file/d/1ArTdaXxzRkDKdbaeroi2NtVLxPZRFrah

**Comment by tomyaacov** [comment]
From what I understand, this version is fixed for Windows and Linux, not for MacOS. When I tried running it on MacOS, the simulation didn't start (black screen). Any chance you can fix it for MacOS as well?

**Comment by GoGitThat** [comment]
I primarily do the development on MacOS so its strange that it isn't working. Can you possibly post the output of the following command after running the simulation (until it fails). "cat ~/Library/Logs/Unity/Player.log" .

**Comment by tomyaacov** [comment]
I saw this subject is being discussed in another issue, i'll post it there.
