### ISSUE TITLE
Game control alerts

### ISSUE THREAD

**Issue by tomyaacov** [mdetools/mdetools19#2]
Is there any way to get alerts on:
- goals
- simulation ends
- suspension starts/ends

**Comment by ValentinBesnard** [comment]
It also would be great to know if the robot has taken the ball (i.e., the ball has been aspired by the robot) ?

**Comment by GoGitThat** [comment]
Hi Valentin, that should be available today!

**Comment by GoGitThat** [comment]
The newest release provides those notifications via a refereePort to which you may listen for updates. The challenge website has been updated with the newest version of the challenge as well as additional instructions (point 3 under the run simulation steps).

**Comment by tomyaacov** [comment]
Great! thanks!
