### ISSUE TITLE
Discrepancy in players name, color, tcp port

### ISSUE THREAD

**Issue by tomyaacov** [mdetools/mdetools19#4]
there appears to be a discrepancy in players name, color, TCP port between the challenge overview [page](https://mdetools.github.io/mdetools19/challengeproblem.html) and the simulation itself. 
Can it be clarified?

**Comment by moji1** [comment]
Hi @tomyaacov 
Thanks a lot for reporting this issue. I have fixed the discrepancy.

Thanks

**Comment by moji1** [comment]
Hi @tomyaacov 
Please let me know if I can close this issue?

Thanks
Mojtaba

**Comment by tomyaacov** [comment]
yeah, thanks!
